version: '3.8'
services:
  dynamodb-local:
    command: '-jar DynamoDBLocal.jar -sharedDb -inMemory'
    image: 'amazon/dynamodb-local:latest'
    container_name: dynamodb-local
    ports:
      - '8000:8000'
    volumes:
      - './create-tables.sh:/docker-entrypoint-initaws.d/create-tables.sh'
    working_dir: /home/dynamodblocal
  aws-cli:
    image: 'amazon/aws-cli:latest'
    container_name: aws-cli
    volumes:
      - './create-tables.sh:/home/dynamodblocal/create-tables.sh'
    working_dir: /home/dynamodblocal
    depends_on:
      - dynamodb-local
    links:
      - dynamodb-local
    entrypoint: /home/dynamodblocal/create-tables.sh
    environment:
      AWS_ACCESS_KEY_ID: DUMMYIDEXAMPLE
      AWS_SECRET_ACCESS_KEY: DUMMYEXAMPLEKEY
      AWS_REGION: us-west-2
  app-node:
    build:
      context: .
      dockerfile: Dockerfile
    image: fitness-tracker-api:latest
    container_name: app-node
    command: npm run start-local
    ports:
      - '3001:3001'
      - '3002:3002'
      - '3003:3003'
      - '3004:3004'
    depends_on:
      - dynamodb-local
    links:
      - dynamodb-local
    environment:
      AWS_ACCESS_KEY_ID: DUMMYIDEXAMPLE
      AWS_SECRET_ACCESS_KEY: DUMMYEXAMPLEKEY
      REGION: us-west-2
      STAGE: local
      USERS_TABLE: USERS_TABLE
      GOALS_TABLE: GOALS_TABLE
      WORKOUT_LOGS_TABLE: WORKOUT_LOGS_TABLE
