service: serverless-todo-api
frameworkVersion: '3'

custom:
  usersTableName: 'users_${sls:stage}'
  goalsTableName: 'goals_${sls:stage}'
  workoutLogTableName: 'workout_logs_${sls:stage}'

provider:
  name: aws
  region: us-west-2
  runtime: nodejs20.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ UsersTable, Arn ]
            - Fn::GetAtt: [ GoalsTable, Arn ]
            - Fn::GetAtt: [ WorkoutLogTable, Arn ]
  environment:
    USERS_TABLE: ${self:custom.usersTableName}
    GOALS_TABLE: ${self:custom.usersTableName}
    WORKOUT_LOGS_TABLE: ${self:custom.usersTableName}

functions:
  users:
    handler: usersFunction.handler
    events:
      - httpApi:
          path: /todos
          method: GET
      - httpApi:
          path: /users
          method: POST
      - httpApi:
          path: /users
          method: GET
      - httpApi:
          path: /users/{id}
          method: GET
      - httpApi:
          path: /users/{id}
          method: PUT
      - httpApi:
          path: /users/{id}
          method: DELETE

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.usersTableName}
    GoalsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: goalId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: goalId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.goalsTableName}
    WorkoutLogTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: logId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: logId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.workoutLogTableName}
